CREATE TABLE Checkouts(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	VALUE DECIMAL(14, 2) NOT NULL,
	JSON_CART LONGTEXT NOT NULL,
	ID_SystemUser BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE Checkouts
ADD CONSTRAINT FK_CHECKOUT_SystemUser
FOREIGN KEY(ID_SystemUser) REFERENCES SystemUsers(ID);
