CREATE TABLE `Author` (
  `AUTHOR_ID` bigint NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AUTHOR_ID`)
);

CREATE TABLE `Book` (
  `SQ_BOOK` bigint NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `PAGES` int DEFAULT NULL,
  `PRICE` decimal(19,2) DEFAULT NULL,
  `RELEASEDATE` datetime NOT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `coverUrl` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SQ_BOOK`)
);

CREATE TABLE `Book_Author` (
  `SQ_BOOK` bigint NOT NULL,
  `AUTHOR_ID` bigint NOT NULL,
  CONSTRAINT FOREIGN KEY (`SQ_BOOK`) REFERENCES `Book` (`SQ_BOOK`),
  CONSTRAINT FOREIGN KEY (`AUTHOR_ID`) REFERENCES `Author` (`AUTHOR_ID`)
);
